# Testing pytorch Cholesky

In [1]:
import torch
import matplotlib.pyplot as plt

In [2]:
def make_random_diagonal_dominant(size=10,batch_size=100):
    """
    Function to construct a diagonal dominant random matrix
    """
    
    A= torch.rand(batch_size,size,size,device='cuda')
    #making the diagonal dominant
    for i in range(size):
        A[:,i,i]  = 1+torch.sum(torch.abs(A[:,i,:]),dim=1)
    return A

In [16]:
A = make_random_diagonal_dominant(5,3)
print(A)

tensor([[[3.5004, 0.5380, 0.4971, 0.7907, 0.0185],
         [0.0540, 3.0303, 0.0239, 0.7700, 0.3132],
         [0.0287, 0.7182, 3.5238, 0.6928, 0.5704],
         [0.7437, 0.5990, 0.3266, 4.0062, 0.8172],
         [0.9077, 0.9815, 0.4275, 0.5531, 4.4022]],

        [[3.0221, 0.1783, 0.8594, 0.4575, 0.2829],
         [0.2101, 2.1971, 0.2284, 0.0640, 0.5432],
         [0.7848, 0.3128, 4.2196, 0.3059, 0.9657],
         [0.5801, 0.4965, 0.2462, 2.8157, 0.1420],
         [0.1951, 0.9597, 0.7358, 0.9871, 3.8941]],

        [[2.8320, 0.5314, 0.0587, 0.5879, 0.1861],
         [0.5568, 3.7999, 0.8690, 0.4276, 0.9031],
         [0.3730, 0.7378, 4.1418, 0.9783, 0.1625],
         [0.4683, 0.4711, 0.4930, 3.3135, 0.5870],
         [0.9159, 0.6682, 0.0150, 0.4420, 3.5741]]], device='cuda:0')


In [25]:
 # Nom we will compute the decomposition

In [17]:
L = torch.cholesky(A,upper=False)
print("intial batch matrix")
print(A[0])

print("chekking the multiplication")
print(torch.matmul(L[0],torch.transpose(L[0],1,0)))

intial batch matrix
tensor([[3.5004, 0.5380, 0.4971, 0.7907, 0.0185],
        [0.0540, 3.0303, 0.0239, 0.7700, 0.3132],
        [0.0287, 0.7182, 3.5238, 0.6928, 0.5704],
        [0.7437, 0.5990, 0.3266, 4.0062, 0.8172],
        [0.9077, 0.9815, 0.4275, 0.5531, 4.4022]], device='cuda:0')
chekking the multiplication
tensor([[3.5004, 0.0540, 0.0287, 0.7437, 0.9077],
        [0.0540, 3.0303, 0.7182, 0.5990, 0.9815],
        [0.0287, 0.7182, 3.5238, 0.3266, 0.4275],
        [0.7437, 0.5990, 0.3266, 4.0062, 0.5531],
        [0.9077, 0.9815, 0.4275, 0.5531, 4.4022]], device='cuda:0')
